services:
  # PostgreSQL DB
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: neatspend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neatspend"]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/neatspend_users?schema=public
      PORT: 3001
      SERVICE_NAME: user-service
      JWT_SECRET: your-development-jwt-secret-change-in-production
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node dist/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # NeatSpend Main API Gateway
  neatspend-api:
    build:
      context: ./services/neatspend-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/neatspend?schema=public
      USER_SERVICE_URL: http://user-service:3001
    depends_on:
      postgres:
        condition: service_healthy
      user-service:
        condition: service_healthy

volumes:
  postgres_data:
