version: "3.8"
services:
  neatspend-api:
    build: ./services/neatspend-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  sms-sync-worker:
    build: ./services/sms-sync-worker
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
  ai-insight-service:
    build: ./services/ai-insight-service
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=development
