issues:
  - title: "[API] Setup User CRUD via Prisma"
    body: "Create user schema in Prisma, setup routes and controller"
    labels: ["backend", "api"]

  - title: "[API] Add logging middleware and global error handler"
    body: "Add logging middleware and a global error handler to the API service."
    labels: ["backend", "api", "logging"]

  - title: "[API] Add healthcheck route"
    body: "Implement a /health route for uptime monitoring."
    labels: ["backend", "api"]

  - title: "[SMS Worker] Ingest messages (mocked source)"
    body: "Set up SMS ingestion from a mocked source for local development."
    labels: ["worker", "sms"]

  - title: "[SMS Worker] Integrate SMS Parser"
    body: "Pipe SMS into parser and store structured data."
    labels: ["worker", "parser"]

  - title: "[AI Service] Basic Gemini API wrapper"
    body: "Create a wrapper for Gemini API calls."
    labels: ["ai", "gemini"]

  - title: "[AI Service] Generate insights from sample transactions"
    body: "Use Gemini to generate insights from sample transaction data."
    labels: ["ai", "gemini"]

  - title: "[Logger] Add log levels + persistent transport (file/Firestore)"
    body: "Enhance neatspend-logger with log levels and persistent transports."
    labels: ["utility", "logger"]

  - title: "[Auth Verifier] Verify Firebase token & extract UID"
    body: "Implement Firebase JWT verification and UID extraction."
    labels: ["utility", "auth"]

  - title: "[SMS Parser] Support Axis, SBI, Paytm, CRED format"
    body: "Add parsing support for major Indian banks and apps."
    labels: ["utility", "parser"]

  - title: "[PubSub Handler] Create base handler with retry logic"
    body: "Create a base Pub/Sub event handler with retry logic."
    labels: ["utility", "pubsub"]

  - title: "[Web] Setup basic Next.js app with Firebase Auth"
    body: "Bootstrap Next.js app and integrate Firebase Auth."
    labels: ["frontend", "web"]

  - title: "[Web] Dashboard UI with expenses list & sync button"
    body: "Build dashboard UI for expenses and sync."
    labels: ["frontend", "web"]

  - title: "[Mobile] Setup React Native + Firebase login"
    body: "Bootstrap React Native app and add Firebase login."
    labels: ["frontend", "mobile"]

  - title: "[Mobile] Sync button and local transaction history"
    body: "Add sync button and show local transaction history."
    labels: ["frontend", "mobile"]

  - title: "Add Dockerfiles for all services"
    body: "Ensure each service has a working Dockerfile."
    labels: ["infra", "docker"]

  - title: "Create Cloud Run YAMLs for services"
    body: "Add deployment YAMLs for Google Cloud Run."
    labels: ["infra", "cloudrun"]

  - title: "Setup pub/sub topics on GCP"
    body: "Create and configure Pub/Sub topics on Google Cloud Platform."
    labels: ["infra", "pubsub"]

  - title: "Setup Firestore + NeonDB schema"
    body: "Design and apply schemas for Firestore and NeonDB."
    labels: ["infra", "db"]

  - title: "Setup ESLint + Prettier in root"
    body: "Add and configure ESLint and Prettier for code quality."
    labels: ["devx", "lint"]

  - title: "Setup Codespaces with full environment"
    body: "Ensure Codespaces works for all services and packages."
    labels: ["devx", "codespaces"]

  - title: "Setup .env config system"
    body: "Standardize environment variable management."
    labels: ["devx", "env"]

  - title: "Add project-wide TypeScript (optional)"
    body: "Migrate or add TypeScript support across the repo."
    labels: ["devx", "typescript"]
