name: bulk-create-issues

on:
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Create issues from YAML
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const issuesFile = '.github/bulk-issues.yml';
            const doc = yaml.load(fs.readFileSync(issuesFile, 'utf8'));
            for (const issue of doc.issues) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                body: issue.body,
                labels: issue.labels
              });
            }
